name: ğŸ™‹ Assign a Member

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  issues: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}
  REPO: ${{ github.repository }}

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ™‹ Choose an Assignee
        run: echo ASSIGNEE=$(shuf -e HaradaTakayuki kazutan1230 Marukome0743 tanePON -n 1) >> $GITHUB_ENV

      - name: ğŸ› Assign Issue
        if: github.event_name == 'issues' && toJSON(github.event.issue.assignees) == '[]'
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: gh issue edit $ISSUE_NUMBER --add-assignee $ASSIGNEE --repo $REPO

      - name: ğŸš€ Assign Pull Request
        if: github.event_name == 'pull_request_target' && toJSON(github.event.pull_request.assignees) == '[]'
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: gh pr edit $PR_NUMBER --add-assignee $ASSIGNEE --repo $REPO
